### ISSUE TITLE
[time] allow one previous semester to be edited

### ISSUE THREAD

**Issue by ramsays** [gradebook/utils#158]
Got feedback from the Corps that it would be nice to be able to edit previous semester to enter final grades, upgrade letters, etc. I know this has already been discussed and we have aligned on allowing students to edit a least one previous semester.

**Comment by joshcosta** [comment]
We need more time™ to think about how to handle server vs. client and creating vs. editing courses. 

Some of the issues we discussed are that server will need to remain more lenient than client with it's ranges, but the client schedule is the source of truth since it is based on the school schedules. 

Editing a previous semester will probably need to be based on separate calculations than the current active semester calculations.

**Comment by vikaspotluri123** [comment]
There's a prototype to allow previous semesters to be writeable, but require explicit opt-in in gradebook/client#420 (nice).

Should we still have a server-side check to prevent creating future semesters?

**Comment by vikaspotluri123** [comment]
The current version of time allows any previous semester to be edited, and our server-side validations do prevent creating courses outside of the active semester(s)
